feat(HACBS-1259): add python script to upload data to pyxis
hacbs-release/release-utils pull request #7
Opened 2023-01-12 21:00 UTC by johnbieren

This commit adds a reworked version of the create-container-image script from the openshift ecosystem team to enable pushing container image metadata to pyxis.

Signed-off-by: Johnny Bieren <jbieren@redhat.com>

2023-01-13 14:33 UTC, scoheb requested changes

2023-01-13 14:33 UTC, scoheb commented on pyxis/create_container_image.py
> +LOGGER = logging.getLogger("operator-cert")
minor...but this does not make sense.

2023-01-13 14:33 UTC, scoheb commented on pyxis/create_container_image.py
> +                "registry": "quay.io",
will this always be true? can't we detect the registry but the pull spec?

2023-01-13 14:33 UTC, scoheb commented on pyxis/pyxis.py
> +LOGGER = logging.getLogger("operator-cert")
same as above

2023-01-13 14:43 UTC, johnbieren commented on pyxis/create_container_image.py
> +LOGGER = logging.getLogger("operator-cert")
Good catch, fixed

2023-01-13 14:43 UTC, johnbieren commented on pyxis/create_container_image.py
> +                "registry": "quay.io",
Fixed, thanks

2023-01-13 14:43 UTC, johnbieren commented on pyxis/pyxis.py
> +LOGGER = logging.getLogger("operator-cert")
Good catch

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    # quote is needed to urlparse the quotation marks
Missing docstring (there's another function with it).

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    return {
Missing docstring (there's another function with it).

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    LOGGER.info("Creating new container image")
Missing docstring (there's another function with it).

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +            "Image with given docker_image_digest doesn't exist yet"
Without breaking the line, this would be shorted than other lines in this very same file.

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +def create_container_image(
Without breaking the line, this would be shorted than other lines in this very same file.

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    docker_image_digest = parsed_data["digest"]
Are you ok with the script failing on runtime if the key doesn't exist?

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    log_level = "DEBUG" if args.verbose else "INFO"
I might be wrong, but I think there are actual variables in `logging` for the different levels. Cleaner if they exist.

2023-01-13 14:48 UTC, davidmogar commented on pyxis/create_container_image.py
> +    exists = check_if_image_already_exists(args, parsed_data["digest"])
A better name could be ``image_eixst` or does_image_exist` maybe as it returns a boolean. You could then use it directly on the if without creating a variable that will not be used afterwards.

2023-01-13 14:48 UTC, davidmogar commented on pyxis/pyxis.py
> +    cert = os.environ.get("PYXIS_CERT_PATH")
Should this two be constants?

2023-01-13 14:48 UTC, davidmogar commented on pyxis/pyxis.py
> +    if auth_required:
Early returns would make this code more manageable.

```
if not auth_required:
    LOGGER.debug("Pyxis session without authentication is created")
    return session

if cert and key:
....
```

2023-01-13 14:50 UTC, johnbieren commented on pyxis/create_container_image.py
> +        default="https://pyxis.stage.engineering.redhat.com",
@scoheb can I put the public endpoint here? Or is it private

2023-01-13 15:08 UTC, johnbieren commented on pyxis/pyxis.py
> +    cert = os.environ.get("PYXIS_CERT_PATH")
not sure what you mean by this

2023-01-13 15:27 UTC, johnbieren commented on pyxis/create_container_image.py
> +    docker_image_digest = parsed_data["digest"]
Yes, it should fail and do nothing if the key doesn't exist. Do you think I should raise a custom exception saying as such in this case, or just leave it and let the normal python failure tell the story?

2023-01-17 14:41 UTC, theflockers commented on pyxis/test_create_container_image.py
> +        "https://catalog.redhat.com/api/containers/v1/images?page_size=1&filter=docker_image_digest%3D%3D%22some_digest%22%3Bnot%28deleted%3D%3Dtrue%29"
should the url be a variable or constant as it repeats several times?

2023-01-17 14:43 UTC, theflockers commented on pyxis/create_container_image.py
> +import argparse
Maybe add the python _shebang_

2023-01-17 15:09 UTC, davidmogar commented on pyxis/create_container_image.py
> +    docker_image_digest = parsed_data["digest"]
Probably a cleaner error would be better, but I'm also ok with leaving it like this. Your call :wink:

2023-01-17 15:10 UTC, davidmogar commented on pyxis/pyxis.py
> +    cert = os.environ.get("PYXIS_CERT_PATH")
The strings (eg. PYXIS_CERT_PATH) being stored in constants.

2023-01-17 19:12 UTC, johnbieren commented on pyxis/create_container_image.py
> +import argparse
fixed

2023-01-17 19:12 UTC, johnbieren commented on pyxis/create_container_image.py
> +    docker_image_digest = parsed_data["digest"]
fixed

2023-01-18 14:09 UTC, davidmogar approved these changes

2023-01-18 14:16 UTC, merged